name: family_health_tracker
description: A family health and kids growth tracker app
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0
  bcrypt: ^1.2.0


  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1
  cloud_functions: ^6.0.6

  # Google Sign In
  google_sign_in: 6.1.6
  sign_in_with_apple: ^7.0.1

  # Monetization
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+8
  in_app_purchase_storekit: ^0.4.8

  # Charts
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^32.2.5

  # UI & Utilities
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.1.0
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  uuid: ^4.5.3
  logger: ^2.6.2
  dio: ^5.9.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  get_it: ^9.2.1
  injectable: ^2.7.1+4


  # PDF Generation
  pdf: ^3.11.3
  printing: ^5.14.2

  smooth_page_indicator: ^2.0.1
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  change_app_package_name: ^1.5.0
  drift_dev:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700
